### PR TITLE
Convert Project to an Unreal plugin

### PR DESCRIPTION
**Pull request by mklabs**
Hi,

The target of the Pull Request is set to `mklabs_plugin` branch you created earlier, so that the main branch stays as a unreal project as it is right now.

This converts the main repo branch from an Unreal Project to a Plugin, that can be installed per project need.

Let me know if there is anything more I can do, if you'd like to receive those changes.

*Note: Unfotunately, due to the amount of changes radically chaning the directory structure, github won't be able to generate a diff. If you'd like to see the shape of the plugin, you can check the fork branch [here](https://github.com/mklabs/UE4_Paragon_Anims_on_Mannequin/tree/plugin)*

### CODE REVIEW

**Comment by mklabs** [comment]
Friendly ping @TCMabe ;)

**Comment by mklabs** [comment]
Thank you Sir. Let me know if everything's working or need anything.

**Comment by TCMabe** [comment]
Will do !

Sir Kai is going to probably use the plugin version for some upcoming work. I will definitely let you know if there are any issues !

Cheers !

**Comment by mklabs** [comment]
Oh nice!

I'm on Kai's discord too, so ping me whenever if need be ;)

**Pull request merged**
